=== ReubenScott/epl-gateway-web/src/main/java/com/kindustry/framework/xsmart/XSmart.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.hongzhitech.com/xml/ns/j2ee/xsmart" xmlns:tns="http://www.hongzhitech.com/xml/ns/j2ee/xsmart">

  <element name="xsmart">
    <complexType>
      <sequence>
        <element name="statement" maxOccurs="unbounded" minOccurs="0">
          <complexType>
            <complexContent>
              <extension base="tns:BaseFieldsType">
                <attribute name="id" type="string" use="required"></attribute>
              </extension>
            </complexContent>
          </complexType>
        </element>
      </sequence>
    </complexType>
  </element>

  <complexType name="BaseFieldsType" mixed="true">
    <choice maxOccurs="unbounded" minOccurs="0">
      <element name="dynamic-field" type="tns:DynamicFieldType" maxOccurs="unbounded" minOccurs="0">
      </element>
      <element name="compare-field" type="tns:CompareFieldType" maxOccurs="unbounded" minOccurs="0">
      </element>
    </choice>
  </complexType>

  <complexType name="DynamicFieldType">
    <complexContent>
      <extension base="tns:BaseFieldsType">
        <attribute name="property" type="string" use="required"></attribute>
        <attribute name="onEmpty" type="tns:BooleanType" use="optional"></attribute>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="CompareFieldType">
    <complexContent>
      <extension base="tns:BaseFieldsType">
        <attribute name="compare" type="tns:CompareType" use="required"></attribute>
        <attribute name="compareProperty" type="string" use="required"></attribute>
        <attribute name="compareValue" type="string" use="required"></attribute>
      </extension>
    </complexContent>
  </complexType>

  <simpleType name="BooleanType">
    <restriction base="string">
      <enumeration value="true"></enumeration>
      <enumeration value="false"></enumeration>
      <enumeration value="yes"></enumeration>
      <enumeration value="no"></enumeration>
    </restriction>
  </simpleType>

  <simpleType name="CompareType">
    <restriction base="string">
      <enumeration value="eq"></enumeration>
      <enumeration value="ne"></enumeration>
      <enumeration value="gt"></enumeration>
      <enumeration value="ge"></enumeration>
      <enumeration value="lt"></enumeration>
      <enumeration value="le"></enumeration>
    </restriction>
  </simpleType>

</schema>

=== ReubenScott/epl-gateway-web/src/main/java/com/kindustry/framework/xsmart/exampleSql.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns:xsmart xmlns:ns="http://www.hongzhitech.com/xml/ns/j2ee/xsmart"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
   xsi:schemaLocation="http://www.hongzhitech.com/xml/ns/j2ee/xsmart XSmart.xsd">
	
    <statement id="testSql">
        select * from test d
        where 1=1
          and d.id = 'someId'
        <dynamic-field property="pro1" >
            and pro1 = #pro1#
        </dynamic-field>
        <dynamic-field property="pro2">
            and pro2 &gt;= #pro2#
        </dynamic-field>
    </statement>
    
    <statement id="findUncheckedMenuByRole">
        with n(SID, MENU_ID, level) as (
            select SID, SID as MENU_ID, 0 from SYS_MENU m
             where 1=1 
            <dynamic-field property="parentId">
                and m.parent_id = '$parentId$'
            </dynamic-field>
            <dynamic-field property="root">
                and m.parent_id is null
            </dynamic-field>
            UNION ALL
            select m.SID, n.MENU_ID, n.level+1 from SYS_MENU m, n
             where m.PARENT_ID=n.SID and level &lt; 10
        )
        select MENU_ID, count(*) as CHILD_CNT
          from n
         where n.level &gt;= 1
           and not exists (
               select 1 from SYS_ROLE_MENU r
                where r.menu_id = n.sid and r.role_id = #roleId#
           )
         group by MENU_ID
    </statement>
    
    <!-- 查询补录记录 -->
    <statement id="amend.queryRecord">
        select $columns$ from $table$ where 1=1 $conditions$ $orderBys$
    </statement>
	
</ns:xsmart>
